### ISSUE TITLE
Make tabs more accessible

### ISSUE THREAD

**Issue by 3y3** [diplodoc-platform/transform#388]
Tabs doesn't support keyboard navigation.

**Comment by martyanovandrey** [comment]
it's already supported for left/right arrow keys and also should support up arrow = left and down arrow = right

**Comment by martyanovandrey** [comment]
done 

https://github.com/diplodoc-platform/tabs-extension/commit/d36f6b625975c76526e88c4bce65e786b2e9f2bf
