### ISSUE TITLE
Make terms more accessible

### ISSUE THREAD

**Issue by 3y3** [diplodoc-platform/transform#389]
We need to add relevant role to term popup.

Also we need to mark term as [live region](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Live_Regions)

**Comment by martyanovandrey** [comment]
done 

https://github.com/diplodoc-platform/transform/commit/7fafa30433d15eb3ab1f5bc56972a3a0da9f1683
