### ISSUE TITLE
Inline code formatting collapses consecutive spaces into single one

### ISSUE THREAD

**Issue by StoneSpb** [diplodoc-platform/transform#455]
I have code snippet with consecutive spaces:
```
#endif  // BUILDFLAG(IS_IOS)
```
When I use inline code formatting the consecutive spaces collapse into single one, which is undesired: `#endif // BUILDFLAG(IS_IOS)`
The behavior is different from code block formatting.

The issue may be caused by using `white-space: normal` style: https://github.com/diplodoc-platform/transform/blob/4d719347e5ca96617a0bf6258f18723245e99433/src/scss/_common.scss#L327

**Comment by shevnv** [comment]
I don't see problems if we add `white-space: pre-wrap;` to inline code to similar behavior with code block.

**Comment by 3y3** [comment]
I also vote to add `white-space: normal;`

**Comment by shevnv** [comment]
> I also vote to add `white-space: normal;`

Looks like, @3y3 copy wrong text `white-space: normal;` and he also wanted change to `white-space: pre-wrap;` )

**Comment by shevnv** [comment]
@StoneSpb could you help us with fix of this problem?

**Comment by StoneSpb** [comment]
Hi, here is the pull-request: https://github.com/diplodoc-platform/transform/pull/513
Please take a look.
