### ISSUE TITLE
Copy icon at block code not working at its border

### ISSUE THREAD

**Issue by saxumcordis** [diplodoc-platform/transform#459]
If I click near to border of copyIcon, onClick does not work

https://github.com/diplodoc-platform/transform/assets/42944548/098384ce-9b9b-4a04-95c1-093aee2b5a53

**Comment by martyanovandrey** [comment]
Where is the code that needs to be corrected located:

https://github.com/diplodoc-platform/transform/blob/master/src/transform/plugins/code.ts
https://github.com/diplodoc-platform/transform/blob/master/src/js/code.ts
https://github.com/diplodoc-platform/transform/blob/master/src/scss/_code.scss

**Comment by martyanovandrey** [comment]
This issue has been resolved with this pull request.
https://github.com/diplodoc-platform/transform/pull/486
