### ISSUE TITLE
Ignore tag "style", if sanitize can't parse CSS inside it

### ISSUE THREAD

**Issue by shevnv** [diplodoc-platform/transform#506]
Now, if sanitize can't parse CSS, it leave this tag as is.
Our security engineer found a problem with svg+style+foreignObject, like this
```html
<svg>
  <style>
    <foreignObject>
       ...some html with xss
    </foreignObject>
  </style>
</svg>
```
My suggestions, add in [catch here](https://github.com/diplodoc-platform/transform/blob/0a7da00f60f5cdfa22b5dad7a9d28603baeb6196/src/transform/sanitize.ts#L563) removing tag "style", if sanitize can't parse CSS inside it.

**Comment by 3y3** [comment]
Fixed in latest versions
